language: node_js
node_js:
  - '7'
services:
  - mongodb
addons:
  code_climate:
    repo_token: '1dfca95f75f16185220d799289afce9e9dbfe6012484cdca0dbe5edc8c4fba74'
notifications:
  email: false
install:
  - yarn install
  - npm run build
  - cd api
  - yarn install
  - npm run build
before_script:
  - npm install -g codeclimate-test-reporter
after_script:
  - codeclimate-test-reporter < api/coverage/lcov.info

