language: node_js
node_js:
  - 'node'
  - '7'
services:
  - mongodb
addons:
  code_climate:
    repo_token: '1dfca95f75f16185220d799289afce9e9dbfe6012484cdca0dbe5edc8c4fba74'
notifications:
  email: false
before_install:
  - npm install -g quasar-cli
install:
  - npm install
  - quasar build
  - cd api
  - npm install
  - npm run build
before_script:
  - npm install -g codeclimate-test-reporter
  - npm install -g quasar-cli
after_script:
  - codeclimate-test-reporter < coverage/lcov.info

